spring.application.name=samplePJ-TODO
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_app
spring.datasource.username=postgres
spring.datasource.password=77nasubi

logging.level.org.mybatis=DEBUG