spring.application.name=samplePJ-TODO
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.sql.init.mode=always
server.error.include-stacktrace=never
server.servlet.session.tracking-modes=cookie